// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewhzqtxkygdhiepzyxuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3aHpxdHhreWdkaGllcHp5eHVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMjQ5NDEsImV4cCI6MjA2NDkwMDk0MX0.N6-PgN_6LnDjKHPyHWRXBI6adCiHc51N2Ze-G0btGys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);